### ISSUE TITLE
After creating new profile, user gets a "No Program Enrollment is available" exception

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1231]
Steps to reproduce:

1. Sign up for the portal using an edX account with no profile. 
2. Complete the profile. Note in particular the program chosen on the first form.
3. Finish the profile and load /dashboard

Result:

![image](https://s3.amazonaws.com/uploads.hipchat.com/151776/1096500/9DDOBY8Ret3M0gO/error.png)

Expected result: 

A complete dashboard with the correct program data displayed. On micromasters-rc, this might look like:

<img width="1013" alt="screen shot 2016-10-04 at 6 54 09 pm" src="https://cloud.githubusercontent.com/assets/430126/19095518/08dc7e8e-8a64-11e6-8e76-a2e41dbbf4ec.png">

Note that if you reload the page after getting the error, it will clear and render as above. 

This seems to only happen with new users.

**Comment by pdpinch** [comment]
observing the logs during the sequence, this is the only exception that comes up:

```
2016-10-04T22:50:41.361652+00:00 app[web.1]: [2016-10-04 22:50:41] DEBUG 20 [django.template] base.py:927 - [178673d1-950f-48ae-b935-3bd7417fb019] - Exception while resolving variable 'style_public_src' in template 'dashboard.html'.
2016-10-04T22:50:41.361681+00:00 app[web.1]: Traceback (most recent call last):
2016-10-04T22:50:41.361683+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 883, in _resolve_lookup
2016-10-04T22:50:41.361683+00:00 app[web.1]:     current = current[bit]
2016-10-04T22:50:41.361684+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/context.py", line 77, in __getitem__
2016-10-04T22:50:41.361685+00:00 app[web.1]:     raise KeyError(key)
2016-10-04T22:50:41.361685+00:00 app[web.1]: KeyError: 'style_public_src'
2016-10-04T22:50:41.361686+00:00 app[web.1]: 
2016-10-04T22:50:41.361687+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2016-10-04T22:50:41.361687+00:00 app[web.1]: 
2016-10-04T22:50:41.361688+00:00 app[web.1]: Traceback (most recent call last):
2016-10-04T22:50:41.361689+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 889, in _resolve_lookup
2016-10-04T22:50:41.361689+00:00 app[web.1]:     if isinstance(current, BaseContext) and getattr(type(current), bit):
2016-10-04T22:50:41.361690+00:00 app[web.1]: AttributeError: type object 'RequestContext' has no attribute 'style_public_src'
2016-10-04T22:50:41.361691+00:00 app[web.1]: 
2016-10-04T22:50:41.361691+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2016-10-04T22:50:41.361692+00:00 app[web.1]: 
2016-10-04T22:50:41.361693+00:00 app[web.1]: Traceback (most recent call last):
2016-10-04T22:50:41.361693+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 898, in _resolve_lookup
2016-10-04T22:50:41.361694+00:00 app[web.1]:     current = current[int(bit)]
2016-10-04T22:50:41.361695+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'style_public_src'
2016-10-04T22:50:41.361695+00:00 app[web.1]: 
2016-10-04T22:50:41.361696+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2016-10-04T22:50:41.361696+00:00 app[web.1]: 
2016-10-04T22:50:41.361697+00:00 app[web.1]: Traceback (most recent call last):
2016-10-04T22:50:41.361697+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 905, in _resolve_lookup
2016-10-04T22:50:41.361698+00:00 app[web.1]:     (bit, current))  # missing attribute
2016-10-04T22:50:41.361700+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [style_public_src] in '[{\'None\': None, \'False\': False, \'True\': True}, {\'request\': <WSGIRequest: GET \'/dashboard/\'>, \'csrf_token\': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7fcd6da35048>>, \'GA_TRACKING_ID\': \'UA-5145472-14\', \'user\': <SimpleLazyObject: <User: pdpinch-mm4>>, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fcd6d79b198>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fcd6d7a72b0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'SUCCESS\': 25, \'WARNING\': 30, \'ERROR\': 40, \'INFO\': 20}}, {}, {\'dashboard_src\': \'/static/bundles/dashboard.js\', \'style_src\': \'/static/bundles/style.js\', \'js_settings_json\': \'{"host": "micromasters-rc.herokuapp.com", "reactGaDebug": false, "search_url": "/api/v0/search/", "edx_base_url": "https://courses.stage.edx.org", "roles": [], "username": "pdpinch-mm4", "gaTrackingID": "UA-5145472-14", "authenticated": true}\'}]'
```

**Comment by noisecapella** [comment]
If the user refreshes the dashboard afterwards, does it fix the problem? I'm feeling like it might be a race condition, haven't tried it out locally yet though

**Comment by pdpinch** [comment]
That is my experience, repeated twice, happened both times.
