### ISSUE TITLE
Unable to upload profile image on mobile (Android 7, Nexus 5X)

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1514]
I'm not sure if there is some error or if the experience is just really slow

**Comment by noisecapella** [comment]
Looks like this is an error. I get a 400 back from the app:

    2016-10-24T14:54:39.682005+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-24T14:54:39.682005+00:00 app[web.1]: 
    2016-10-24T14:54:39.682005+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.682007+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 891, in _resolve_lookup
    2016-10-24T14:54:39.682008+00:00 app[web.1]:     current = getattr(current, bit)
    2016-10-24T14:54:39.682008+00:00 app[web.1]: AttributeError: 'dict' object has no attribute 'hide_label'
    2016-10-24T14:54:39.682008+00:00 app[web.1]: 
    2016-10-24T14:54:39.682009+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-24T14:54:39.682009+00:00 app[web.1]: 
    2016-10-24T14:54:39.682009+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.682010+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 898, in _resolve_lookup
    2016-10-24T14:54:39.682010+00:00 app[web.1]:     current = current[int(bit)]
    2016-10-24T14:54:39.682011+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'hide_label'
    2016-10-24T14:54:39.682011+00:00 app[web.1]: 
    2016-10-24T14:54:39.682012+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-24T14:54:39.682012+00:00 app[web.1]: 
    2016-10-24T14:54:39.682013+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.682013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 905, in _resolve_lookup
    2016-10-24T14:54:39.682014+00:00 app[web.1]:     (bit, current))  # missing attribute
    2016-10-24T14:54:39.682016+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in "{'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x7f1f17ca4a20>, 'base_template': 'input.html', 'template_pack': 'rest_framework/horizontal', 'input_type': 'file'}"
    2016-10-24T14:54:39.683078+00:00 app[web.1]: [2016-10-24 14:54:39] DEBUG 12 [django.template] base.py:927 - [ff304bd0-1201-4b05-8ab9-d89024734159] - Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
    2016-10-24T14:54:39.683079+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.683080+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 883, in _resolve_lookup
    2016-10-24T14:54:39.683080+00:00 app[web.1]:     current = current[bit]
    2016-10-24T14:54:39.683080+00:00 app[web.1]: KeyError: 'placeholder'
    2016-10-24T14:54:39.683081+00:00 app[web.1]: 
    2016-10-24T14:54:39.683081+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-24T14:54:39.683082+00:00 app[web.1]: 
    2016-10-24T14:54:39.683082+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.683083+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 891, in _resolve_lookup
    2016-10-24T14:54:39.683083+00:00 app[web.1]:     current = getattr(current, bit)
    2016-10-24T14:54:39.683084+00:00 app[web.1]: AttributeError: 'dict' object has no attribute 'placeholder'
    2016-10-24T14:54:39.713452+00:00 heroku[router]: at=info method=PATCH path="/api/v0/profiles/gschneel_renamed/" host=micromasters-ci-pr-1460.herokuapp.com request_id=26c4c1d4-f354-4b44-9554-87baab16665c fwd="172.56.34.81" dyno=web.1 connect=1ms service=243ms status=400 bytes=19254
    2016-10-24T14:54:39.683129+00:00 app[web.1]: 
    2016-10-24T14:54:39.683139+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-24T14:54:39.683139+00:00 app[web.1]: 
    2016-10-24T14:54:39.683140+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.683140+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 898, in _resolve_lookup
    2016-10-24T14:54:39.683141+00:00 app[web.1]:     current = current[int(bit)]
    2016-10-24T14:54:39.683141+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'placeholder'
    2016-10-24T14:54:39.683141+00:00 app[web.1]: 
    2016-10-24T14:54:39.683142+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2016-10-24T14:54:39.683142+00:00 app[web.1]: 
    2016-10-24T14:54:39.683142+00:00 app[web.1]: Traceback (most recent call last):
    2016-10-24T14:54:39.683143+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/template/base.py", line 905, in _resolve_lookup
    2016-10-24T14:54:39.683143+00:00 app[web.1]:     (bit, current))  # missing attribute
    2016-10-24T14:54:39.683146+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in "{'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x7f1f17ca4a20>, 'base_template': 'input.html', 'template_pack': 'rest_framework/horizontal', 'input_type': 'file'}"
    2016-10-24T14:54:39.721435+00:00 app[web.1]: {address space usage: 525139968 bytes/500MB} {rss usage: 72925184 bytes/69MB} [pid: 12|app: 0|req: 80/135] 10.13.217.57 () {58 vars in 1292 bytes} [Mon Oct 24 14:54:39 2016] PATCH /api/v0/profiles/gschneel_renamed/ => generated 19096 bytes in 241 msecs (HTTP/1.1 400) 4 headers in 158 bytes (1 switches on core 0)
    2016-10-24T14:54:44.080066+00:00 heroku[router]: at=info method=GET path="/api/v0/profiles/gschneel_renamed/" host=micromasters-ci-pr-1460.herokuapp.com request_id=4a501fa5-49d3-49df-9aeb-85077714b7f6 fwd="172.56.34.81" dyno=web.1 connect=1ms service=36ms status=200 bytes=1415
    2016-10-24T14:54:44.084576+00:00 app[web.1]: {address space usage: 525139968 bytes/500MB} {rss usage: 72925184 bytes/69MB} [pid: 12|app: 0|req: 81/136] 10.43.152.216 () {52 vars in 1113 bytes} [Mon Oct 24 14:54:44 2016] GET /api/v0/profiles/gschneel_renamed/ => generated 1274 bytes in 35 msecs (HTTP/1.1 200) 4 headers in 141 bytes (1 switches on core 0)

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190472886/

**Comment by amir-qayyum-khan** [comment]
issue not produces on android 6 marshmallow, huawei honor 5x

**Comment by amir-qayyum-khan** [comment]
tested on nexus 6p android 7 very thing is working fine.

For testing i used https://micromasters-rc.herokuapp.com/?next=/dashboard/
