### ISSUE TITLE
seed_db requires libraries in test_requirements.txt which aren't available for PR builds

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1745]
~ $ ./manage.py seed_db
    Traceback (most recent call last):
      File "./manage.py", line 14, in <module>
        execute_from_command_line(sys.argv)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
        utility.execute()
      File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
        klass = load_command_class(app_name, subcommand)
      File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
        module = import_module('%s.management.commands.%s' % (app_name, name))
      File "/app/.heroku/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/app/seed_data/management/commands/seed_db.py", line 8, in <module>
        from factory.django import mute_signals
    ImportError: No module named 'factory'

**Comment by amir-qayyum-khan** [comment]
didnt understand it.
this command ``docker-compose run web ./manage.py seed_db`` is running fine.

**Comment by noisecapella** [comment]
I'm talking about PR builds, see the title of this issue

**Comment by noisecapella** [comment]
@gsidebo Can you make a PR that just covers this issue? This is blocking other issues

**Comment by gsidebo** [comment]
i can, but keep in mind that we can manually install factory-boy and faker via pip on any heroku instance. i dont think this should be a blocker

**Comment by gsidebo** [comment]
@noisecapella fyi https://github.com/mitodl/micromasters/pull/1832
