### ISSUE TITLE
custom_exception_handler turning 401 errors into 500 errors

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1783]
2016-11-16T16:55:48.277699+00:00 app[web.1]: 2016-11-16 16:55:48.277 30 LOG C-0x25418f0: db1/atqdcgkjjvfsps@127.0.0.1:46985 login attempt: db=db1 user=atqdcgkjjvfsps tls=no
    2016-11-16T16:55:48.358510+00:00 app[web.1]: An exception was intercepted by custom_exception_handler
    2016-11-16T16:55:48.358513+00:00 app[web.1]: Traceback (most recent call last):
    2016-11-16T16:55:48.358515+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/views.py", line 465, in dispatch
    2016-11-16T16:55:48.358515+00:00 app[web.1]:     self.initial(request, *args, **kwargs)
    2016-11-16T16:55:48.358516+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/views.py", line 387, in initial
    2016-11-16T16:55:48.358516+00:00 app[web.1]:     self.perform_authentication(request)
    2016-11-16T16:55:48.358517+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/views.py", line 313, in perform_authentication
    2016-11-16T16:55:48.358518+00:00 app[web.1]:     request.user
    2016-11-16T16:55:48.358519+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/request.py", line 379, in __getattribute__
    2016-11-16T16:55:48.358519+00:00 app[web.1]:     return super(Request, self).__getattribute__(attr)
    2016-11-16T16:55:48.358520+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/request.py", line 196, in user
    2016-11-16T16:55:48.358521+00:00 app[web.1]:     self._authenticate()
    2016-11-16T16:55:48.358525+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/request.py", line 342, in _authenticate
    2016-11-16T16:55:48.358526+00:00 app[web.1]:     user_auth_tuple = authenticator.authenticate(self)
    2016-11-16T16:55:48.358527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/authentication.py", line 86, in authenticate
    2016-11-16T16:55:48.358528+00:00 app[web.1]:     return self.authenticate_credentials(userid, password)
    2016-11-16T16:55:48.358528+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/authentication.py", line 99, in authenticate_credentials
    2016-11-16T16:55:48.358529+00:00 app[web.1]:     raise exceptions.AuthenticationFailed(_('Invalid username/password.'))
    2016-11-16T16:55:48.358534+00:00 app[web.1]: rest_framework.exceptions.AuthenticationFailed: Invalid username/password.

**Comment by pdpinch** [comment]
This is different from #1713 isn't it?

**Comment by noisecapella** [comment]
I'm going to close this since I didn't see this on @giocalitri's computer
