### ISSUE TITLE
checkout API returns 500 error when course missing edX course key

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1868]
This is another one of those errors that should never happen -- it only did because I was testing and I set an enrollment start date in the past for a course run with no course key. 

I'm not sure it's worth fixing, but if it ever did happen in the wild, it would be a better UX to display an error to the user that encourages them to contact us, and log an `ImproperlyConfigured` exception instead of a causing a 500. 

### Steps to Reproduce

1. Create a course run in a FA program with an enrollment start date in the past, but no course key
2. Calculate your personalized price and click the "Pay Now" button

### Expected results

Learner is directed to Cybersource for checkout

### Actual results

The API returns a 500, but nothing happens in the browser. 

A traceback appears in the logs, something like this: 

```
2016-11-27T19:57:40.340816+00:00 app[web.1]: An exception was intercepted by custom_exception_handler
2016-11-27T19:57:40.340820+00:00 app[web.1]: Traceback (most recent call last):
2016-11-27T19:57:40.340821+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
2016-11-27T19:57:40.340822+00:00 app[web.1]:     response = handler(request, *args, **kwargs)
2016-11-27T19:57:40.340822+00:00 app[web.1]:   File "./ecommerce/views.py", line 58, in post
2016-11-27T19:57:40.340823+00:00 app[web.1]:     edx_course_key=course_id,
2016-11-27T19:57:40.340824+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/shortcuts.py", line 85, in get_object_or_404
2016-11-27T19:57:40.340825+00:00 app[web.1]:     return queryset.get(*args, **kwargs)
2016-11-27T19:57:40.340825+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 389, in get
2016-11-27T19:57:40.340826+00:00 app[web.1]:     (self.model._meta.object_name, num)
2016-11-27T19:57:40.340827+00:00 app[web.1]: courses.models.MultipleObjectsReturned: get() returned more than one CourseRun -- it returned 8!
2016-11-27T19:57:44.294863+00:00 heroku[router]: at=info method=POST path="/api/v0/checkout/" host=micromasters-rc.herokuapp.com request_id=e705eb7d-69c4-4124-b37d-1cf5e55ad098 fwd="107.77.225.91" dyno=web.1 connect=1ms service=3992ms status=500 bytes=13644
2016-11-27T19:57:44.213122+00:00 app[web.1]: [2016-11-27 19:57:44] ERROR 46 [django.request] exception.py:124 - [f035cf1e-6d60-4e55-8887-f38e83b68f0f] - Internal Server Error: /api/v0/checkout/
2
```

This is because there are typically multiple course runs with an empty course key (any run that has a start date but doesn't exist on edX yet).

**Comment by pdpinch** [comment]
Ok, this API returns a 404 now if the course key is null. The front-end doesn't do anything to handle it though. 

Perhaps a bigger issue is that the order summary won't render if the course key is null. 

![screenshot-micromasters-rc herokuapp com-2017-04-05-16-30-26](https://cloud.githubusercontent.com/assets/430126/24725510/37ca6640-1a1d-11e7-9bc3-4f3685d2007c.png)
