### ISSUE TITLE
500 error when viewing dashboard

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#195]
2016-04-20T19:09:23.663101+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2016-04-20T19:09:23.663092+00:00 app[web.1]: Traceback (most recent call last):
2016-04-20T19:09:23.663094+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
2016-04-20T19:09:23.663055+00:00 app[web.1]: [2016-04-20 19:09:23] ERROR 17 [django.request] base.py:284 - [f7777331-6509-4625-80a1-d4e5aba9a338] - Internal Server Error: /api/v0/dashboard/
2016-04-20T19:09:23.663102+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
2016-04-20T19:09:23.663103+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-04-20T19:09:23.663105+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2016-04-20T19:09:23.663105+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2016-04-20T19:09:23.663104+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_django.py", line 499, in wrapper
2016-04-20T19:09:23.663107+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
2016-04-20T19:09:23.663108+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2016-04-20T19:09:23.663106+00:00 app[web.1]:     return view_func(*args, **kwargs)
2016-04-20T19:09:23.663111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
2016-04-20T19:09:23.663109+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/newrelic-2.54.0.41/newrelic/hooks/component_djangorestframework.py", line 27, in _nr_wrapper_APIView_dispatch_
2016-04-20T19:09:23.663110+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2016-04-20T19:09:23.663112+00:00 app[web.1]:     response = self.handle_exception(exc)
2016-04-20T19:09:23.663112+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
2016-04-20T19:09:23.663113+00:00 app[web.1]:     response = handler(request, *args, **kwargs)
2016-04-20T19:09:23.663113+00:00 app[web.1]:   File "./dashboard/views.py", line 54, in get
2016-04-20T19:09:23.663114+00:00 app[web.1]:     response_data['courses'].sort(key=lambda x: x['position_in_program'])
2016-04-20T19:09:23.663121+00:00 app[web.1]: TypeError: unorderable types: NoneType() < NoneType()
2016-04-20T19:09:23.693891+00:00 app[web.1]: {address space usage: 517779456 bytes/493MB} {rss usage: 57561088 bytes/54MB} [pid: 17|app: 0|req: 2/64] 10.166.174.36 () {56 vars in 1089 bytes} [Wed Apr 20 19:09:23 2016] GET /api/v0/dashboard/ => generated 27 bytes in 503 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)

**Comment by noisecapella** [comment]
@giocalitri says this was caused by `position_in_program` being `None`. We are requiring the admin to set this value properly when editing the course in Django admin
