### ISSUE TITLE
faker not importable on micromasters-ci and micromasters-rc

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2313]
➜  micromasters git:(master) heroku run bash --app micromasters-ci        
    Running bash on ⬢ micromasters-ci... up, run.5747 (Hobby)
    ~ $ ./manage.py shell
    Python 3.5.2 (default, Jun 28 2016, 18:49:03) 
    [GCC 4.8.4] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    (InteractiveConsole)
    >>> import factory
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/app/.heroku/python/lib/python3.5/site-packages/factory/__init__.py", line 42, in <module>
        from .faker import Faker
      File "/app/.heroku/python/lib/python3.5/site-packages/factory/faker.py", line 41, in <module>
        import faker
    ImportError: No module named 'faker'
    >>> 

From the chat in Slack we probably just need to upgrade a dependency

**Comment by pdpinch** [comment]
This has blocked some testing on rc and production.

**Comment by noisecapella** [comment]
This appears to be resolved
