### ISSUE TITLE
[exam] Command `authorization_user_exam` crashed because of using user id instead of object 

### ISSUE THREAD

**Issue by amir-qayyum-khan** [mitodl/micromasters#2445]
see https://github.com/mitodl/micromasters/blob/master/exams/management/commands/authorization_user_exam.py#L60

```python
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/app/exams/management/commands/authorization_user_exam.py", line 72, in handle
    authorize_for_exam(mmtrack, enrollment.course_run)
  File "/app/exams/utils.py", line 36, in authorize_for_exam
    ExamProfile.objects.get_or_create(profile=mmtrack.user.profile)
AttributeError: 'int' object has no attribute 'profile'
```

@pdpinch

**Comment by amir-qayyum-khan** [comment]
Issue ripple from issue on #2331 
RC #2435
