### ISSUE TITLE
Financial aid task does not check for open exchange URL before making a request

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#2556]
I was seeing odd tracebacks when trying to run the Micromasters app locally:
```
celery_1   | [2017-02-13 15:32:03,082: ERROR/MainProcess] Task financialaid.tasks.sync_currency_exchange_rates[1b5e2284-c582-4f0f-bb95-1b123f3985cf] raised unexpected: MissingSchema("Invalid URL 'Nonelatest.json?app_id=': No schema supplied. Perhaps you meant http://Nonelatest.json?app_id=?",)
celery_1   | Traceback (most recent call last):
celery_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
celery_1   |     R = retval = fun(*args, **kwargs)
celery_1   |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
celery_1   |     return self.run(*args, **kwargs)
celery_1   |   File "/src/financialaid/tasks.py", line 18, in sync_currency_exchange_rates
celery_1   |     resp = requests.get(CURRENCY_EXCHANGE_RATE_API_REQUEST_URL)
celery_1   |   File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 70, in get
celery_1   |     return request('get', url, params=params, **kwargs)
celery_1   |   File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 56, in request
celery_1   |     return session.request(method=method, url=url, **kwargs)
celery_1   |   File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 461, in request
celery_1   |     prep = self.prepare_request(req)
celery_1   |   File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 394, in prepare_request
celery_1   |     hooks=merge_hooks(request.hooks, self.hooks),
celery_1   |   File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 294, in prepare
celery_1   |     self.prepare_url(url, params)
celery_1   |   File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 354, in prepare_url
celery_1   |     raise MissingSchema(error)
celery_1   | requests.exceptions.MissingSchema: Invalid URL 'Nonelatest.json?app_id=': No schema supplied. Perhaps you meant http://Nonelatest.json?app_id=?
```

After tracing through the exception, I found that the problem was that the `sync_currency_exchange_rates` task was trying to make an HTTP request to an invalid URL, and the URL was invalid because `settings.OPEN_EXCHANGE_RATES_URL` was unset. If this setting is unset, the system should display a helpful and informative error message, instead of this misleading and confusing one.

**Comment by amir-qayyum-khan** [comment]
this is assigned to no one and it is in prgress?
@pdpinch

**Comment by pdpinch** [comment]
@singingwolfboy has a PR open. I think her forgot to assign this to himself.
