### ISSUE TITLE
Can't create ExamAuthorization for user because of final grade error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2796]
When trying to run the management command `./manage.py authorization_user_exam --username=Rephaelh` I get the following output:

```
Either exam_module is not set for course id="8" or user="Rephaelh" has no enrollment(s)
Either exam_module is not set for course id="9" or user="Rephaelh" has no enrollment(s)
Either exam_module is not set for course id="11" or user="Rephaelh" has no enrollment(s)
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/app/exams/management/commands/authorization_user_exam.py", line 50, in handle
    username=username
  File "/app/exams/utils.py", line 180, in bulk_authorize_for_exam
    authorize_for_exam_given_program(program, username)
  File "/app/exams/utils.py", line 212, in authorize_for_exam_given_program
    authorize_for_latest_passed_course(mmtrack, course_id)
  File "/app/exams/utils.py", line 242, in authorize_for_latest_passed_course
    mmtrack.has_passed_course(edx_course_key) and
  File "/app/dashboard/utils.py", line 259, in has_passed_course
    final_grade = self.extract_final_grade(course_id)
  File "/app/dashboard/utils.py", line 216, in extract_final_grade
    status=FinalGradeStatus.COMPLETE,
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
grades.models.DoesNotExist: FinalGrade matching query does not exist.
```

**Comment by rhysyngsun** [comment]
Specifically [this code](https://github.com/mitodl/micromasters/blob/master/exams/utils.py#L241-L244) is checking differently than [this code](https://github.com/mitodl/micromasters/blob/master/exams/utils.py#L108). We shouldn't have 2 different copies of this logic.

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you take a look at this asap?

I can reproduce the error on micromasters-rc, with a slightly different result:

```
Peters-MBP-2:micromasters pdpinch$ heroku run --app micromasters-rc ./manage.py authorization_user_exam --all
Running ./manage.py authorization_user_exam --all on ⬢ micromasters-rc... up, run.1182 (Hobby)
Unable to authorize user: pdpinch for exam on course_id: 8
Traceback (most recent call last):
  File "/app/exams/utils.py", line 249, in authorize_for_latest_passed_course
    authorize_for_exam(mmtrack, enrollment.course_run)
  File "/app/exams/utils.py", line 136, in authorize_for_exam
    raise ExamAuthorizationException(errors_message)
exams.utils.ExamAuthorizationException: 
[Exam authorization] Unable to authorize user "pdpinch" for exam,
Course id is "course-v1:MITx+14.100x+3T2016". Either user has not passed course or already authorize.

Either exam_module is not set for course id="9" or user="pdpinch" has no enrollment(s)
Either exam_module is not set for course id="10" or user="pdpinch" has no enrollment(s)
Either exam_module is not set for course id="11" or user="pdpinch" has no enrollment(s)
Either exam_module is not set for course id="7" or user="pdpinch" has no enrollment(s)
.
.
.
Either exam_module is not set for course id="8" or user="Jared-QA-Last-Day" has no enrollment(s)
Either exam_module is not set for course id="9" or user="Jared-QA-Last-Day" has no enrollment(s)
Either exam_module is not set for course id="10" or user="Jared-QA-Last-Day" has no enrollment(s)
Either exam_module is not set for course id="11" or user="Jared-QA-Last-Day" has no enrollment(s)
Either exam_module is not set for course id="7" or user="Jared-QA-Last-Day" has no enrollment(s)
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/app/exams/management/commands/authorization_user_exam.py", line 45, in handle
    bulk_authorize_for_exam()
  File "/app/exams/utils.py", line 180, in bulk_authorize_for_exam
    authorize_for_exam_given_program(program, username)
  File "/app/exams/utils.py", line 212, in authorize_for_exam_given_program
    authorize_for_latest_passed_course(mmtrack, course_id)
  File "/app/exams/utils.py", line 242, in authorize_for_latest_passed_course
    mmtrack.has_passed_course(edx_course_key) and
  File "/app/dashboard/utils.py", line 259, in has_passed_course
    final_grade = self.extract_final_grade(course_id)
  File "/app/dashboard/utils.py", line 216, in extract_final_grade
    status=FinalGradeStatus.COMPLETE,
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
grades.models.DoesNotExist: FinalGrade matching query does not exist.
