### ISSUE TITLE
Fix test warning

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#343]
App
        ✓ clears profile, ui, and dashboard after unmounting (165ms)
        profile completeness
          ✓ redirects to /profile if profile is not complete (316ms)
    Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
    Arguments: [object Object]
    Error
        at Function.createFromInputFallback (/home/george/Projects/micromasters/node_modules/moment/moment.js:271:105)
        at configFromString (/home/george/Projects/micromasters/node_modules/moment/moment.js:1169:32)
        at configFromInput (/home/george/Projects/micromasters/node_modules/moment/moment.js:1675:13)
        at prepareConfig (/home/george/Projects/micromasters/node_modules/moment/moment.js:1658:13)
        at createFromConfig (/home/george/Projects/micromasters/node_modules/moment/moment.js:1625:44)
        at createLocalOrUTC (/home/george/Projects/micromasters/node_modules/moment/moment.js:1707:16)
        at local__createLocal (/home/george/Projects/micromasters/node_modules/moment/moment.js:1711:16)
        at utils_hooks__hooks (/home/george/Projects/micromasters/node_modules/moment/moment.js:16:29)
        at dateFormat (EmploymentTab.js:213:30)
        at EmploymentTab.jobRow (EmploymentTab.js:224:15)
        at EmploymentTab.js:164:63
        at Array.map (native)
        at EmploymentTab.renderWorkHistory (EmploymentTab.js:164:40)
        at EmploymentTab.render (EmploymentTab.js:288:21)
        at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:687:34)
        at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:707:32)
        at [object Object].wrapper [as _renderValidatedComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at [object Object].ReactCompositeComponentMixin.performInitialMount (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:291:30)
        at [object Object].ReactCompositeComponentMixin.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:222:21)
        at [object Object].wrapper [as mountComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:39:35)
        at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:203:44)
        at ReactDOMComponent.Mixin._createInitialChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:628:32)
        at ReactDOMComponent.Mixin.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:474:12)
        at ReactDOMComponent.wrapper [as mountComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:39:35)
        at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:203:44)
        at ReactDOMComponent.Mixin._createInitialChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:628:32)
        at ReactDOMComponent.Mixin.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:474:12)
        at ReactDOMComponent.wrapper [as mountComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:39:35)
        at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:203:44)
        at ReactDOMComponent.Mixin._createInitialChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:628:32)
        at ReactDOMComponent.Mixin.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:474:12)
        at ReactDOMComponent.wrapper [as mountComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:39:35)
        at [object Object].ReactCompositeComponentMixin.performInitialMount (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:297:34)
        at [object Object].ReactCompositeComponentMixin.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:222:21)
        at [object Object].wrapper [as mountComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:39:35)
        at [object Object].ReactCompositeComponentMixin.performInitialMount (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:297:34)
        at [object Object].ReactCompositeComponentMixin.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:222:21)
        at [object Object].wrapper [as mountComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:39:35)
        at ReactDOMComponent.ReactMultiChild.Mixin._mountChildAtIndex (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:379:40)
        at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:299:43)
        at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:259:12)
        at ReactDOMComponent.Mixin._updateDOMChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:845:12)
        at ReactDOMComponent.Mixin.updateComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:691:10)
        at ReactDOMComponent.Mixin.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:647:10)
        at ReactDOMComponent.wrapper [as receiveComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:103:22)
        at Object.ReactChildReconciler.updateChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactChildReconciler.js:85:25)
        at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:178:32)
        at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:271:31)
        at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactMultiChild.js:259:12)
        at ReactDOMComponent.Mixin._updateDOMChildren (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:845:12)
        at ReactDOMComponent.Mixin.updateComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:691:10)
        at ReactDOMComponent.Mixin.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactDOMComponent.js:647:10)
        at ReactDOMComponent.wrapper [as receiveComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:103:22)
        at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:661:23)
        at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:643:10)
        at [object Object].ReactCompositeComponentMixin.updateComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:572:12)
        at [object Object].wrapper [as updateComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:495:10)
        at Object.ReactReconciler.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:103:22)
        at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:661:23)
        at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:643:10)
        at [object Object].ReactCompositeComponentMixin.updateComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:572:12)
        at [object Object].wrapper [as updateComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:495:10)
        at Object.ReactReconciler.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:103:22)
        at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:661:23)
        at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:643:10)
        at [object Object].ReactCompositeComponentMixin.updateComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:572:12)
        at [object Object].wrapper [as updateComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:495:10)
        at Object.ReactReconciler.receiveComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:103:22)
        at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:661:23)
        at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:643:10)
        at [object Object].ReactCompositeComponentMixin.updateComponent (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:572:12)
        at [object Object].wrapper [as updateComponent] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/home/george/Projects/micromasters/node_modules/react/lib/ReactCompositeComponent.js:511:12)
        at Object.ReactReconciler.performUpdateIfNecessary (/home/george/Projects/micromasters/node_modules/react/lib/ReactReconciler.js:122:22)
        at runBatchedUpdates (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:143:21)
        at ReactReconcileTransaction.Mixin.perform (/home/george/Projects/micromasters/node_modules/react/lib/Transaction.js:136:20)
        at ReactUpdatesFlushTransaction.Mixin.perform (/home/george/Projects/micromasters/node_modules/react/lib/Transaction.js:136:20)
        at ReactUpdatesFlushTransaction._assign.perform (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:89:38)
        at flushBatchedUpdates (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:165:19)
        at wrapper (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at ReactUpdatesFlushTransaction.NESTED_UPDATES.close (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:47:7)
        at ReactUpdatesFlushTransaction.Mixin.closeAll (/home/george/Projects/micromasters/node_modules/react/lib/Transaction.js:202:25)
        at ReactUpdatesFlushTransaction.Mixin.perform (/home/george/Projects/micromasters/node_modules/react/lib/Transaction.js:149:16)
        at ReactUpdatesFlushTransaction._assign.perform (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:89:38)
        at Object.flushBatchedUpdates (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:165:19)
        at Object.wrapper [as flushBatchedUpdates] (/home/george/Projects/micromasters/node_modules/react/lib/ReactPerf.js:66:21)
        at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/home/george/Projects/micromasters/node_modules/react/lib/Transaction.js:202:25)
        at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/george/Projects/micromasters/node_modules/react/lib/Transaction.js:149:16)
        at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/george/Projects/micromasters/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
        at Object.enqueueUpdate (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdates.js:194:22)
        at enqueueUpdate (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdateQueue.js:22:16)
        at Object.ReactUpdateQueue.enqueueSetState (/home/george/Projects/micromasters/node_modules/react/lib/ReactUpdateQueue.js:201:5)
        at Connect.ReactComponent.setState (/home/george/Projects/micromasters/node_modules/react/lib/ReactComponent.js:67:16)
        at Connect.handleChange (/home/george/Projects/micromasters/node_modules/react-redux/lib/components/connect.js:301:14)
        at dispatch (/home/george/Projects/micromasters/node_modules/redux/lib/createStore.js:186:19)
        at /home/george/Projects/micromasters/node_modules/redux-asserts/lib/index.js:131:16
        at /home/george/Projects/micromasters/node_modules/redux-thunk/lib/index.js:15:14
        at dispatch (/home/george/Projects/micromasters/node_modules/redux/lib/applyMiddleware.js:45:18)
        at index.js:100:20
          ✓ redirects to /profile/professional if a field is missing there (173ms)
          ✓ doesn't check work_history if currently_employed = 'no' (88ms)
          ✓ checks work_history if currently_employed = 'yes' (128ms)
          ✓ redirects to /profile/privacy if a field is missing there (103ms)
          ✓ sets a dialog with appropriate text for personal info (274ms)
          ✓ sets a dialog with appropriate text for professional info (135ms)
          ✓ sets a dialog with appropriate text for privacy info (107ms)

**Comment by noisecapella** [comment]
It looks like this is due to the user profile constant not having default work history or education information.

**Comment by aliceriot** [comment]
ah, I think Amir added those in #314
