### ISSUE TITLE
Elasticsearch certificate error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3814]
2018-02-08T16:17:08.461481+00:00 app[web.1]: Traceback (most recent call last):
    2018-02-08T16:17:08.461483+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    2018-02-08T16:17:08.461485+00:00 app[web.1]:     response = get_response(request)
    2018-02-08T16:17:08.461488+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
    2018-02-08T16:17:08.461486+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    2018-02-08T16:17:08.461490+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    2018-02-08T16:17:08.461491+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    2018-02-08T16:17:08.461493+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_django.py", line 527, in wrapper
    2018-02-08T16:17:08.461495+00:00 app[web.1]:     return wrapped(*args, **kwargs)
    2018-02-08T16:17:08.461496+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    2018-02-08T16:17:08.461498+00:00 app[web.1]:     return view_func(*args, **kwargs)
    2018-02-08T16:17:08.461500+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    2018-02-08T16:17:08.461502+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
    2018-02-08T16:17:08.461503+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/component_djangorestframework.py", line 38, in _nr_wrapper_APIView_dispatch_
    2018-02-08T16:17:08.461505+00:00 app[web.1]:     return wrapped(*args, **kwargs)
    2018-02-08T16:17:08.461507+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/views.py", line 477, in dispatch
    2018-02-08T16:17:08.461508+00:00 app[web.1]:     response = self.handle_exception(exc)
    2018-02-08T16:17:08.461510+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/views.py", line 437, in handle_exception
    2018-02-08T16:17:08.461512+00:00 app[web.1]:     self.raise_uncaught_exception(exc)
    2018-02-08T16:17:08.461513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/views.py", line 474, in dispatch
    2018-02-08T16:17:08.461515+00:00 app[web.1]:     response = handler(request, *args, **kwargs)
    2018-02-08T16:17:08.461517+00:00 app[web.1]:   File "./search/views.py", line 48, in post
    2018-02-08T16:17:08.461518+00:00 app[web.1]:     return self._execute_search_from_request(request.user, request.data)
    2018-02-08T16:17:08.461520+00:00 app[web.1]:   File "./search/views.py", line 35, in _execute_search_from_request
    2018-02-08T16:17:08.461522+00:00 app[web.1]:     results = prepare_and_execute_search(user, search_param_dict=request_data)
    2018-02-08T16:17:08.461523+00:00 app[web.1]:   File "./search/api.py", line 187, in prepare_and_execute_search
    2018-02-08T16:17:08.461525+00:00 app[web.1]:     filter_on_email_optin=filter_on_email_optin,
    2018-02-08T16:17:08.461526+00:00 app[web.1]:   File "./search/api.py", line 139, in create_search_obj
    2018-02-08T16:17:08.461530+00:00 app[web.1]:   File "./search/connection.py", line 188, in get_default_alias_and_doc_type
    2018-02-08T16:17:08.461532+00:00 app[web.1]:     return get_aliases_and_doc_types(index_type)[0]
    2018-02-08T16:17:08.461536+00:00 app[web.1]:     conn = get_conn(verify=False)
    2018-02-08T16:17:08.461528+00:00 app[web.1]:     index, doc_type = get_default_alias_and_doc_type(index_type)
    2018-02-08T16:17:08.461534+00:00 app[web.1]:   File "./search/connection.py", line 146, in get_aliases_and_doc_types
    2018-02-08T16:17:08.461538+00:00 app[web.1]:   File "./search/connection.py", line 57, in get_conn
    2018-02-08T16:17:08.461539+00:00 app[web.1]:     verify_certs=use_ssl
    2018-02-08T16:17:08.461546+00:00 app[web.1]:     self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
    2018-02-08T16:17:08.461541+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch_dsl/connections.py", line 66, in create_connection
    2018-02-08T16:17:08.461551+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 157, in set_connections
    2018-02-08T16:17:08.461543+00:00 app[web.1]:     conn = self._conns[alias] = Elasticsearch(**kwargs)
    2018-02-08T16:17:08.461545+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 170, in __init__
    2018-02-08T16:17:08.461553+00:00 app[web.1]:     connections = list(zip(connections, hosts))
    2018-02-08T16:17:08.461555+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 154, in _create_connection
    2018-02-08T16:17:08.461556+00:00 app[web.1]:     return self.connection_class(**kwargs)
    2018-02-08T16:17:08.461548+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/transport.py", line 108, in __init__
    2018-02-08T16:17:08.461550+00:00 app[web.1]:     self.set_connections(hosts)
    2018-02-08T16:17:08.461558+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in __init__
    2018-02-08T16:17:08.461559+00:00 app[web.1]:     raise ImproperlyConfigured("Root certificates are missing for certificate "
    2018-02-08T16:17:08.461561+00:00 app[web.1]: elasticsearch.exceptions.ImproperlyConfigured: Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.

**Comment by noisecapella** [comment]
To reproduce just run `search.connection.get_conn()`

**Comment by noisecapella** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/439765277/
