### ISSUE TITLE
upgrade to django 2.1

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4150]
django 2.1 supports a view only permission in the admin. Having a view-only permission would allow me to give admin access (to certain models) to the MicroMasters staff, allowing them to look up data to solve support issues instead of me doing it.

**Comment by amir-qayyum-khan** [comment]
@pdpinch wagtail is not accepting this change.

```Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/micromasters/urls.py", line 6, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "/usr/local/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 11, in <module>
    from wagtail.admin.urls import password_reset as wagtailadmin_password_reset_urls
  File "/usr/local/lib/python3.6/site-packages/wagtail/admin/urls/password_reset.py", line 4, in <module>
    from wagtail.admin.views import account
  File "/usr/local/lib/python3.6/site-packages/wagtail/admin/views/account.py", line 92, in <module>
    password_reset = _wrap_password_reset_view(auth_views.password_reset)
AttributeError: module 'django.contrib.auth.views' has no attribute 'password_reset'```

**Comment by pdpinch** [comment]
According to the Wagtail docs they support 2.1:

https://github.com/wagtail/wagtail/blob/master/README.md#compatibility

If you can't figure out why it's failing, we could try opening an issue with wagtail. 

This isn't a critical update, but it would be nice to have. Don't spend more than an hour (more) on this.

**Comment by amir-qayyum-khan** [comment]
@pdpinch it seems that version/master is not released.

The latest version on git https://github.com/wagtail/wagtail/blob/v2.2.2/README.md Do not support 2.1.x

**Comment by pdpinch** [comment]
Ok. I guess we should wait until the current master version is released.

**Comment by pdpinch** [comment]
Wagtail 2.3 was released today and it claims django 2.1 support. 

(you could also update paramiko while you're at it)

**Comment by amir-qayyum-khan** [comment]
sure@pdpinch

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am stuck on `edx-api-client==0.5.0     requires python-dateutil==2.5.3, requests==2.11.1, six==1.10.0` 
should i update six on `edx-api-client`.
https://github.com/mitodl/edx-api-client/blob/master/requirements.txt#L3

### I am running command
`docker-compose run --rm web pip-compile -vv requirements.in`
