### ISSUE TITLE
Unable to run recreate_index

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#779]
I'm getting this error:

    ➜  micromasters git:(master) drun ./manage.py recreate_index
    System check identified some issues:
    
    WARNINGS:
    ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
    HEAD /micromasters/user [status:404 request:0.001s]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    psycopg2.ProgrammingError: relation "dashboard_cachedcertificate" does not exist
    LINE 1: ..."dashboard_cachedcertificate"."last_request" FROM "dashboard...
                                                                 ^
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "./manage.py", line 14, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
        output = self.handle(*args, **options)
      File "/src/search/management/commands/recreate_index.py", line 22, in handle
        recreate_index()
      File "/src/search/api.py", line 287, in recreate_index
        index_users(User.objects.iterator())
      File "/src/search/api.py", line 126, in index_users
        count += _index_users_chunk(chunk)
      File "/src/search/api.py", line 95, in _index_users_chunk
        doc_type=USER_DOC_TYPE,
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 188, in bulk
        for ok, item in streaming_bulk(client, actions, **kwargs):
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 159, in streaming_bulk
        for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 53, in _chunk_actions
        for action, data in actions:
      File "/src/search/api.py", line 93, in <genexpr>
        (serialize_user(user) for user in users),
      File "/src/search/api.py", line 165, in serialize_user
        certificate.data for certificate in user.cachedcertificate_set.all().exclude(data__isnull=True)
      File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 258, in __iter__
        self._fetch_all()
      File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
        self._result_cache = list(self.iterator())
      File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
        results = compiler.execute_sql()
      File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
        cursor.execute(sql, params)
      File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "dashboard_cachedcertificate" does not exist
    LINE 1: ..."dashboard_cachedcertificate"."last_request" FROM "dashboard...
                                                                 ^

**Comment by noisecapella** [comment]
Nevermind, looks like old data from the cached certificates PR when I was working on it
