### ISSUE TITLE
Error when deleting existing fake users

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#818]
➜  micromasters git:(813_fake_user_birth_country) drun ./manage.py delete_realistic_search_data
    System check identified some issues:
    
    WARNINGS:
    ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
    DELETE /micromasters/program_user/61 [status:404 request:0.009s]
    DELETE /micromasters/program_user/60 [status:404 request:0.006s]
    DELETE /micromasters/program_user/59 [status:404 request:0.006s]
    DELETE /micromasters/program_user/58 [status:404 request:0.006s]
    DELETE /micromasters/program_user/57 [status:404 request:0.006s]
    DELETE /micromasters/program_user/56 [status:404 request:0.010s]
    DELETE /micromasters/program_user/55 [status:404 request:0.009s]
    DELETE /micromasters/program_user/54 [status:404 request:0.005s]
    DELETE /micromasters/program_user/53 [status:404 request:0.006s]
    DELETE /micromasters/program_user/52 [status:404 request:0.010s]
    DELETE /micromasters/program_user/51 [status:404 request:0.006s]
    DELETE /micromasters/program_user/50 [status:404 request:0.009s]
    DELETE /micromasters/program_user/49 [status:404 request:0.009s]
    DELETE /micromasters/program_user/48 [status:404 request:0.010s]
    DELETE /micromasters/program_user/47 [status:404 request:0.006s]
    DELETE /micromasters/program_user/46 [status:404 request:0.005s]
    DELETE /micromasters/program_user/45 [status:404 request:0.006s]
    DELETE /micromasters/program_user/44 [status:404 request:0.006s]
    DELETE /micromasters/program_user/43 [status:404 request:0.006s]
    DELETE /micromasters/program_user/42 [status:404 request:0.006s]
    DELETE /micromasters/program_user/41 [status:404 request:0.006s]
    DELETE /micromasters/program_user/40 [status:404 request:0.005s]
    DELETE /micromasters/program_user/39 [status:404 request:0.006s]
    DELETE /micromasters/program_user/38 [status:404 request:0.006s]
    DELETE /micromasters/program_user/37 [status:404 request:0.013s]
    DELETE /micromasters/program_user/36 [status:404 request:0.006s]
    DELETE /micromasters/program_user/35 [status:404 request:0.006s]
    DELETE /micromasters/program_user/34 [status:404 request:0.010s]
    DELETE /micromasters/program_user/33 [status:404 request:0.005s]
    DELETE /micromasters/program_user/32 [status:404 request:0.006s]
    DELETE /micromasters/program_user/29 [status:404 request:0.006s]
    DELETE /micromasters/program_user/28 [status:404 request:0.006s]
    DELETE /micromasters/program_user/27 [status:404 request:0.006s]
    DELETE /micromasters/program_user/26 [status:404 request:0.006s]
    DELETE /micromasters/program_user/25 [status:404 request:0.006s]
    DELETE /micromasters/program_user/24 [status:404 request:0.009s]
    DELETE /micromasters/program_user/23 [status:404 request:0.006s]
    DELETE /micromasters/program_user/22 [status:404 request:0.006s]
    DELETE /micromasters/program_user/20 [status:404 request:0.006s]
    DELETE /micromasters/program_user/19 [status:404 request:0.005s]
    DELETE /micromasters/program_user/18 [status:404 request:0.006s]
    DELETE /micromasters/program_user/17 [status:404 request:0.006s]
    DELETE /micromasters/program_user/16 [status:404 request:0.006s]
    DELETE /micromasters/program_user/15 [status:404 request:0.006s]
    DELETE /micromasters/program_user/14 [status:404 request:0.006s]
    DELETE /micromasters/program_user/13 [status:404 request:0.006s]
    DELETE /micromasters/program_user/12 [status:404 request:0.006s]
    DELETE /micromasters/program_user/11 [status:404 request:0.005s]
    DELETE /micromasters/program_user/10 [status:404 request:0.010s]
    DELETE /micromasters/program_user/9 [status:404 request:0.006s]
    DELETE /micromasters/program_user/8 [status:404 request:0.006s]
    DELETE /micromasters/program_user/7 [status:404 request:0.006s]
    DELETE /micromasters/program_user/6 [status:404 request:0.005s]
    DELETE /micromasters/program_user/5 [status:404 request:0.006s]
    DELETE /micromasters/program_user/4 [status:404 request:0.006s]
    DELETE /micromasters/program_user/3 [status:404 request:0.006s]
    DELETE /micromasters/program_user/2 [status:404 request:0.006s]
    DELETE /micromasters/program_user/1 [status:404 request:0.006s]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 160, in __get__
        rel_obj = getattr(instance, self.cache_name)
    AttributeError: 'CourseRun' object has no attribute '_course_cache'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "./manage.py", line 14, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
        output = self.handle(*args, **options)
      File "/src/profiles/management/commands/delete_realistic_search_data.py", line 18, in handle
        Program.objects.filter(description__startswith=FAKE_PROGRAM_DESC_PREFIX).delete()
      File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 600, in delete
        deleted, _rows_count = collector.delete()
      File "/usr/local/lib/python3.5/site-packages/django/db/models/deletion.py", line 316, in delete
        sender=model, instance=obj, using=self.using
      File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 192, in send
        response = receiver(signal=self, sender=sender, **named)
      File "/src/dashboard/signals.py", line 103, in handle_delete_certificate
        program = instance.course_run.course.program
      File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 169, in __get__
        rel_obj = qs.get()
      File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
        self.model._meta.object_name

**Comment by gsidebo** [comment]
signals problem. i thought i fixed this one..... ill have a look

**Comment by gsidebo** [comment]
@noisecapella this is a tough one to debug without reproducing. can you reproduce it reliably?
